# Step 09 - Tip - Testing Exceptions with Junit `assertThrows`

En esta lección vamos a probar las Excepciones en JUnit. Vamos a escribir otro método en base al método **`length_basic()`**.

<img width="1359" alt="image" src="https://user-images.githubusercontent.com/23094588/206924668-ef78bde0-9df2-4a82-9fc6-2c90339c2bdc.png">

Aunque realmente no tenemos ningún assert nuestro test no ha pasado como sucedia en ejemplos anteriores que no tenian assert, aquí tenemos una barra roja, esto es por que al ejecutarse el código se produce una excepción **`java.lang.NullPointerException`** ya que **`str = null`**.

Para probar excepciones con JUnit tenemos la anotación **`assertThrows`** sabemos que por un lado la excepción esperada es **`NullPointerException.class`** este sería nuestro primer parámetro para colocar el segundo parámetro nos vamos a ayudar de la programación funcional como sigue:

<img width="1230" alt="image" src="https://user-images.githubusercontent.com/23094588/206925563-35ea6186-ff49-4433-8680-270d25825c84.png">

Como podemos ver el Test pasa por que ambas excepciones generadas son las mismas.

Podríamos pensar no usar la progración funcional y simplemente poner el código como sigue:

<img width="773" alt="image" src="https://user-images.githubusercontent.com/23094588/206925682-f357eff2-8a3f-404d-8737-1e67557aae82.png">

Pero como podemos ver nos marca un error de compilación ya que muestra el mensaje de error:

**`The method assertThrows(Class<T>, Executable) in the type Assertions is not applicable for the arguments (Class<NullPointerException>, 
int)`**  

<img width="816" alt="image" src="https://user-images.githubusercontent.com/23094588/206925803-9563c923-f245-4a07-89ac-810d043df67d.png">

El resultado de **`str.length()`** es un **`int`** y lo que se espera es un **`Executable`** y eso lo logramos con la expresión lambda que teniamos antes.

<img width="1226" alt="image" src="https://user-images.githubusercontent.com/23094588/206925971-bdc09e62-8895-490f-a6cf-86b793f2aded.png">

¿Qué pasa si le damos un valor a **`str`**.

<img width="1226" alt="image" src="https://user-images.githubusercontent.com/23094588/206926056-d9f52614-3f86-4021-bc27-580da6180805.png">

El test no lo pasa ya que nos indica que **`Expected java.lang.NullPointerException to be thrown, but nothing was thrown.`**. Se esperaba **`NullPointerException`** pero no se lanzo porque ya no tenemos excepción.

Lo que estamos probando aquí es que para cadenas nulas el método **`length()`** lanza la excepción **`NullPointerException`**, cosa que hemos comprobado. Así que la anotación **`assertThrows`** nos permite comparar excepciones.
